export const styles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    background: '#0f172a',
    fontFamily: 'system-ui, sans-serif',
    padding: '2rem 1rem',
  },
  nav: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '1.5rem',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  navButton: (active) => ({
    padding: '0.5rem 1rem',
    borderRadius: '8px',
    border: 'none',
    background: active ? '#6366f1' : '#1e293b',
    color: '#f1f5f9',
    cursor: 'pointer',
    fontSize: '0.9rem',
  }),
  card: {
    background: '#1e293b',
    padding: '2rem',
    borderRadius: '12px',
    width: '90%',
    maxWidth: '480px',
    boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
  },
  wideCard: {
    background: '#1e293b',
    padding: '2rem',
    borderRadius: '12px',
    width: '90%',
    maxWidth: '720px',
    boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
  },
  heading: { color: '#f1f5f9', marginBottom: '1.5rem', textAlign: 'center' },
  form: { display: 'flex', flexDirection: 'column', gap: '0.75rem' },
  input: {
    padding: '0.75rem',
    borderRadius: '8px',
    border: '1px solid #334155',
    background: '#0f172a',
    color: '#f1f5f9',
    fontSize: '1rem',
  },
  button: {
    padding: '0.75rem',
    borderRadius: '8px',
    border: 'none',
    background: '#6366f1',
    color: 'white',
    fontSize: '1rem',
    cursor: 'pointer',
  },
  linkButton: {
    background: 'none',
    border: 'none',
    color: '#818cf8',
    cursor: 'pointer',
    fontSize: '0.9rem',
    textDecoration: 'underline',
    padding: 0,
  },
  error: { color: '#f87171', marginTop: '1rem' },
  success: { color: '#4ade80', marginTop: '1rem' },
  result: {
    marginTop: '1.5rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    background: '#0f172a',
    padding: '0.75rem 1rem',
    borderRadius: '8px',
    gap: '0.75rem',
  },
  copyButton: {
    padding: '0.4rem 0.8rem',
    borderRadius: '6px',
    border: 'none',
    background: '#334155',
    color: '#f1f5f9',
    cursor: 'pointer',
    flexShrink: 0,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    color: '#f1f5f9',
    fontSize: '0.9rem',
  },
  th: {
    textAlign: 'left',
    padding: '0.5rem',
    borderBottom: '1px solid #334155',
    color: '#94a3b8',
    fontWeight: 500,
  },
  td: {
    padding: '0.5rem',
    borderBottom: '1px solid #334155',
    wordBreak: 'break-all',
  },
  deleteButton: {
    padding: '0.3rem 0.6rem',
    borderRadius: '6px',
    border: 'none',
    background: '#7f1d1d',
    color: '#fecaca',
    cursor: 'pointer',
    fontSize: '0.8rem',
  },
  analyticsButton: {
    padding: '0.3rem 0.6rem',
    borderRadius: '6px',
    border: 'none',
    background: '#334155',
    color: '#c7d2fe',
    cursor: 'pointer',
    fontSize: '0.8rem',
    marginRight: '0.4rem',
  },
  breakdownCard: {
    background: '#0f172a',
    borderRadius: '8px',
    padding: '1rem',
    marginTop: '1rem',
  },
  breakdownTitle: {
    color: '#94a3b8',
    fontSize: '0.9rem',
    fontWeight: 500,
    marginBottom: '0.5rem',
  },
  breakdownGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '1rem',
    marginTop: '1rem',
  },
};
